[features]
seeds = false
skip-lint = false
[programs.localnet]
soap_dispenser = "SDGQRX2DBX3qDNjEnEyryXFsGj2Sq6NXJd2SmZ3kfJ6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-dispenser = "ts-node ./scripts/init.ts"
get-tree-prices = "ts-node ./scripts/getTreePrices.ts"
init-idl = "node ./scripts/initIdl.js"