[features]
seeds = false
skip-lint = false
[programs.devnet]
soap_dispenser = "sdp7bhcJ2TmGuHVqYNYFXLdSCNtqBu8heVoyYavkpyb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-dispenser = "ts-node ./scripts/init.ts"
get-tree-prices = "ts-node ./scripts/getTreePrices.ts"
init-idl = "node ./scripts/initIdl.js"
mint = "ts-node ./scripts/mint.ts"
get-asset = "ts-node ./scripts/getAsset.ts"
fund-pot = "ts-node ./scripts/fundPot.ts"
withdraw-pot = "ts-node ./scripts/withdrawPot.ts"
get-dispensers = "ts-node ./scripts/getDispensers.ts"
